services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: thessinfo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./BackEnd/ThessInfo       # uppercase ‘B’ and ‘T’
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd/ThessInfo:/app
    environment:
      DJANGO_CORS_ALLOWED_ORIGINS: "http://localhost:3060"
    env_file:
      - ./BackEnd/ThessInfo/.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8060:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/ThessInfo     # uppercase ‘F’ and ‘T’
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/ThessInfo:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: "http://localhost:8060"
    command: npm run dev -- --host 0.0.0.0 --port 3000
    ports:
      - "3060:3000"
    depends_on:
      - backend

volumes:
  pgdata: