# Generated by Django 5.1.7 on 2025-04-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spatial_ref', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('no2_conc', models.FloatField()),
                ('o3_conc', models.FloatField()),
                ('co_conc', models.FloatField()),
                ('no_conc', models.FloatField()),
                ('so2_conc', models.FloatField()),
            ],
        ),
    ]
